name: 4kvideodownloaderplus-tsugu
base: core24
version: '25.4.3'
summary: Free video downloader trusted by millions
description: |
  Main functionality of our applications is free and will always stay free. No watermarks, no registration, no payments. Premium features are available for advanced use. 

grade: stable
confinement: strict

lint:
  ignore:
    - classic
    - library
    
platforms:
  amd64:
  
apps:
  4kvideodownloaderplus-tsugu:
    command: usr/lib/4kvideodownloaderplus/4kvideodownloaderplus-bin
    extensions: [gnome]
    environment: 
      LD_LIBRARY_PATH: $SNAP/usr/lib/4kvideodownloaderplus:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libproxy:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR
      HOME: "$SNAP_USER_DATA"
      DISABLE_WAYLAND: 1  
    plugs:
      - home
      - audio-playback
      - network
      - removable-media
      - unity7
      - browser-support
      # I removed some plugs because as it turns out they area autoconnected by the gnome extension.

parts:
  4kvideodownloaderplus-tsugu:
    source: https://dl.4kdownload.com/app/4kvideodownloaderplus_${SNAPCRAFT_PROJECT_VERSION}_amd64.deb
    plugin: dump
    source-type: deb
    stage-packages:
      - libc6
      - libstdc++6
      - libproxy1v5
      - libxkbfile1
      - libxcb-cursor0
      - libxkbcommon0
